---@type dropbar_configs_t
local opts = {
  icons = {
    kinds = {
      symbols = {
        Array = "󰅪 ",
        BlockMappingPair = "󰅩 ",
        Boolean = " ",
        BreakStatement = "󰙧 ",
        Call = "󰃷 ",
        CaseStatement = "󱃙 ",
        Class = " ",
        Color = "󰏘 ",
        Constant = "󰏿 ",
        Constructor = " ",
        ContinueStatement = "→ ",
        Copilot = " ",
        Declaration = "󰙠 ",
        Delete = "󰩺 ",
        DoStatement = "󰑖 ",
        Element = "󰅩 ",
        Enum = " ",
        EnumMember = " ",
        Event = " ",
        Field = " ",
        File = "󰈔 ",
        Folder = "󰉋 ",
        ForStatement = "󰑖 ",
        Function = "󰊕 ",
        GotoStatement = "󰁔 ",
        Identifier = "󰀫 ",
        IfStatement = "󰇉 ",
        Interface = " ",
        Keyword = "󰌋 ",
        List = "󰅪 ",
        Log = "󰦪 ",
        Lsp = " ",
        Macro = "󰁌 ",
        MarkdownH1 = "󰉫 ",
        MarkdownH2 = "󰉬 ",
        MarkdownH3 = "󰉭 ",
        MarkdownH4 = "󰉮 ",
        MarkdownH5 = "󰉯 ",
        MarkdownH6 = "󰉰 ",
        Method = "󰆧 ",
        Module = "󰏗 ",
        Namespace = "󰅩 ",
        Null = "󰢤 ",
        Number = "󰎠 ",
        Object = "󰅩 ",
        Operator = "󰆕 ",
        Package = "󰆦 ",
        Pair = "󰅪 ",
        Property = " ",
        Reference = "󰦾 ",
        Regex = " ",
        Repeat = "󰑖 ",
        Return = "󰌑 ",
        RuleSet = "󰅩 ",
        Scope = "󰅩 ",
        Section = "󰅩 ",
        Snippet = "󰩫 ",
        Specifier = "󰦪 ",
        Statement = "󰅩 ",
        String = "󰉾 ",
        Struct = " ",
        SwitchStatement = "󰺟 ",
        Table = "󰅩 ",
        Terminal = " ",
        Text = " ",
        Type = " ",
        TypeParameter = "󰆩 ",
        Unit = " ",
        Value = "󰎠 ",
        Variable = "󰀫 ",
        WhileStatement = "󰑖 ",
      },
    },
    ui = {
      bar = {
        separator = " ",
        extends = "…",
      },
      menu = {
        separator = " ",
        indicator = " ",
      },
    },
  },
}

return opts
