---@type LazyKeysSpec[]
local keys = {
  -- XXX: SEP
  {
    "<leader>,",
    ":PickMe buffers<cr>",
    mode = "n",
    desc = "Buffers",
    { noremap = true, silent = true },
  },
  {
    "<leader>/",
    ":PickMe search_history<cr>",
    mode = "n",
    desc = "Search History",
    { noremap = true, silent = true },
  },
  {
    "<leader>:",
    ":PickMe command_history<cr>",
    mode = "n",
    desc = "Command History",
    { noremap = true, silent = true },
  },
  {
    "<leader><space>",
    ":PickMe files<cr>",
    mode = "n",
    desc = "Files",
    { noremap = true, silent = true },
  },
  {
    "<C-f>",
    ":PickMe files<cr>",
    mode = "n",
    desc = "Files",
    { noremap = true, silent = true },
  },
  {
    "<leader>fa",
    ":PickMe files<cr>",
    mode = "n",
    desc = "Find Files",
    { noremap = true, silent = true },
  },
  {
    "<leader>fb",
    ":PickMe buffers<cr>",
    mode = "n",
    desc = "Buffers",
    { noremap = true, silent = true },
  },
  {
    "<leader>fc",
    ":PickMe git_log_file<cr>",
    mode = "n",
    desc = "File Commits",
    { noremap = true, silent = true },
  },
  {
    "<leader>fd",
    ":PickMe projects<cr>",
    mode = "n",
    desc = "Project Dirs",
    { noremap = true, silent = true },
  },
  {
    "<leader>ff",
    ":PickMe git_files<cr>",
    mode = "n",
    desc = "Find Git Files",
    { noremap = true, silent = true },
  },
  {
    "<leader>fg",
    ":PickMe live_grep<cr>",
    mode = "n",
    desc = "Grep",
    { noremap = true, silent = true },
  },
  {
    "<leader>fl",
    ":PickMe loclist<cr>",
    mode = "n",
    desc = "Location List",
    { noremap = true, silent = true },
  },
  {
    "<leader>fm",
    ":PickMe git_status<cr>",
    mode = "n",
    desc = "Modified Files",
    { noremap = true, silent = true },
  },
  {
    "<leader>fo",
    ":PickMe grep_buffers<cr>",
    mode = "n",
    desc = "Grep Open Buffers",
    { noremap = true, silent = true },
  },
  {
    "<leader>fp",
    ":PickMe resume<cr>",
    mode = "n",
    desc = "Previous Picker",
    { noremap = true, silent = true },
  },
  {
    "<leader>fq",
    ":PickMe quickfix<cr>",
    mode = "n",
    desc = "Quickfix List",
    { noremap = true, silent = true },
  },
  {
    "<leader>fr",
    ":PickMe oldfiles<cr>",
    mode = "n",
    desc = "Recent Files",
    { noremap = true, silent = true },
  },
  {
    "<leader>fs",
    ":PickMe buffer_grep<cr>",
    mode = "n",
    desc = "Buffer Lines",
    { noremap = true, silent = true },
  },
  {
    "<leader>ft",
    ":PickMe pickers<cr>",
    mode = "n",
    desc = "All Pickers",
    { noremap = true, silent = true },
  },
  {
    "<leader>fu",
    ":PickMe undo<cr>",
    mode = "n",
    desc = "Undo History",
    { noremap = true, silent = true },
  },
  {
    "<leader>fw",
    ":PickMe grep_string<cr>",
    mode = "n",
    desc = "Word Grep",
    { noremap = true, silent = true },
  },
  {
    "<leader>fz",
    ":PickMe zoxide<cr>",
    mode = "n",
    desc = "Zoxide",
    { noremap = true, silent = true },
  },
  -- XXX: SEP
  {
    "<leader>gL",
    ":PickMe git_log<cr>",
    mode = "n",
    desc = "Git Log",
    { noremap = true, silent = true },
  },
  {
    "<leader>gS",
    ":PickMe git_stash<cr>",
    mode = "n",
    desc = "Git Stash",
    { noremap = true, silent = true },
  },
  {
    "<leader>gc",
    ":PickMe git_commits<cr>",
    mode = "n",
    desc = "Git Commits",
    { noremap = true, silent = true },
  },
  {
    "<leader>gl",
    ":PickMe git_log_line<cr>",
    mode = "n",
    desc = "Git Log Line",
    { noremap = true, silent = true },
  },
  {
    "<leader>gs",
    ":PickMe git_branches<cr>",
    mode = "n",
    desc = "Git Branches",
    { noremap = true, silent = true },
  },
  -- XXX: SEP
  {
    "<leader>ii",
    ":PickMe icons<cr>",
    mode = "n",
    desc = "Icons",
    { noremap = true, silent = true },
  },
  {
    "<leader>ir",
    ":PickMe registers<cr>",
    mode = "n",
    desc = "Registers",
    { noremap = true, silent = true },
  },
  {
    "<leader>is",
    ":PickMe spell_suggest<cr>",
    mode = "n",
    desc = "Spell Suggestions",
    { noremap = true, silent = true },
  },
  {
    "<leader>iv",
    ":PickMe cliphist<cr>",
    mode = "n",
    desc = "Clipboard",
    { noremap = true, silent = true },
  },
  -- XXX: SEP
  {
    "<leader>lD",
    ":PickMe lsp_declarations<cr>",
    mode = "n",
    desc = "LSP Declarations",
    { noremap = true, silent = true },
  },
  {
    "<leader>lF",
    ":PickMe lsp_references<cr>",
    mode = "n",
    desc = "References",
    { noremap = true, silent = true },
  },
  {
    "<leader>lL",
    ":PickMe diagnostics<cr>",
    mode = "n",
    desc = "Diagnostics",
    { noremap = true, silent = true },
  },
  {
    "<leader>lS",
    ":PickMe lsp_workspace_symbols<cr>",
    mode = "n",
    desc = "Workspace Symbols",
    { noremap = true, silent = true },
  },
  {
    "<leader>ld",
    ":PickMe lsp_definitions<cr>",
    mode = "n",
    desc = "LSP Definitions",
    { noremap = true, silent = true },
  },
  {
    "<leader>li",
    ":PickMe lsp_implementations<cr>",
    mode = "n",
    desc = "LSP Implementations",
    { noremap = true, silent = true },
  },
  {
    "<leader>ll",
    ":PickMe diagnostics_buffer<cr>",
    mode = "n",
    desc = "Buffer Diagnostics",
    { noremap = true, silent = true },
  },
  {
    "<leader>ls",
    ":PickMe lsp_document_symbols<cr>",
    mode = "n",
    desc = "Document Symbols",
    { noremap = true, silent = true },
  },
  {
    "<leader>lt",
    ":PickMe lsp_type_definitions<cr>",
    mode = "n",
    desc = "Type Definitions",
    { noremap = true, silent = true },
  },
  -- XXX: SEP
  {
    "<leader>oC",
    ":PickMe colorschemes<cr>",
    mode = "n",
    desc = "Colorschemes",
    { noremap = true, silent = true },
  },
  {
    "<leader>oa",
    ":PickMe autocmds<cr>",
    mode = "n",
    desc = "Autocmds",
    { noremap = true, silent = true },
  },
  {
    "<leader>oc",
    ":PickMe command_history<cr>",
    mode = "n",
    desc = "Command History",
    { noremap = true, silent = true },
  },
  {
    "<leader>od",
    ":PickMe help<cr>",
    mode = "n",
    desc = "Docs",
    { noremap = true, silent = true },
  },
  {
    "<leader>of",
    ":PickMe marks<cr>",
    mode = "n",
    desc = "Marks",
    { noremap = true, silent = true },
  },
  {
    "<leader>og",
    ":PickMe commands<cr>",
    mode = "n",
    desc = "Commands",
    { noremap = true, silent = true },
  },
  {
    "<leader>oh",
    ":PickMe highlights<cr>",
    mode = "n",
    desc = "Highlights",
    { noremap = true, silent = true },
  },
  {
    "<leader>oj",
    ":PickMe jumplist<cr>",
    mode = "n",
    desc = "Jump List",
    { noremap = true, silent = true },
  },
  {
    "<leader>ok",
    ":PickMe keymaps<cr>",
    mode = "n",
    desc = "Keymaps",
    { noremap = true, silent = true },
  },
  {
    "<leader>ol",
    ":PickMe lazy<cr>",
    mode = "n",
    desc = "Search for Plugin Spec",
    { noremap = true, silent = true },
  },
  {
    "<leader>om",
    ":PickMe man<cr>",
    mode = "n",
    desc = "Man Pages",
    { noremap = true, silent = true },
  },
  {
    "<leader>on",
    ":PickMe notifications<cr>",
    mode = "n",
    desc = "Notifications",
    { noremap = true, silent = true },
  },
  {
    "<leader>oo",
    ":PickMe options<cr>",
    mode = "n",
    desc = "Options",
    { noremap = true, silent = true },
  },
  {
    "<leader>os",
    ":PickMe search_history<cr>",
    mode = "n",
    desc = "Search History",
    { noremap = true, silent = true },
  },
  {
    "<leader>ot",
    ":PickMe treesitter<cr>",
    mode = "n",
    desc = "Treesitter Find",
    { noremap = true, silent = true },
  },
  -- XXX: SEP
  {
    "<leader>ecc",
    function()
      require("pickme").pick("files", { cwd = vim.fn.stdpath("config"), title = "Neovim Configs" })
    end,
    mode = "n",
    desc = "Neovim Configs",
    { noremap = true, silent = true },
  },
  {
    "<leader>ecP",
    function()
      require("pickme").pick("files", { cwd = vim.fn.stdpath("data") .. "/lazy", title = "Plugin Files" })
    end,
    mode = "n",
    desc = "Neovim Plugins",
    { noremap = true, silent = true },
  },
  {
    "<leader>ecL",
    function()
      require("pickme").pick("files", { cwd = vim.fn.stdpath("state"), title = "Log Files" })
    end,
    mode = "n",
    desc = "Neovim Logs",
    { noremap = true, silent = true },
  },
}

return keys
