---@type table
local cmds = {
  "EcoEcologPeek",
  "EcologAWSConfig",
  "EcologCopy",
  "EcologDebugFiles",
  "EcologDebugState",
  "EcologEnvGet",
  "EcologEnvSet",
  "EcologFzf",
  "EcologGenerateExample",
  "EcologGoto",
  "EcologGotoVar",
  "EcologHealth",
  "EcologInterpolationToggle",
  "EcologPeek",
  "EcologRecover",
  "EcologRefresh",
  "EcologSagaGD",
  "EcologSagaHover",
  "EcologSelect",
  "EcologShellToggle",
  "EcologShelter",
  "EcologShelterLinePeek",
  "EcologShelterToggle",
  "EcologSnacks",
  "EcologTelescope",
  "EcologVaultConfig",
  "EcologWorkspaceCurrent",
  "EcologWorkspaceList",
  "EcologWorkspaceSwitch",
}

return cmds
