require("config.commands")
require("config.base")
require("config.options")
require("config.clipboard")
--require("config.more-options")
require("config.plugin-manager")
require("config.autocmds")
require("config.keymaps")
