---@type table
local opts = {
  scroll_preview = {
    scroll_down = "<C-f>",
    scroll_up = "<C-b>",
  },
  request_timeout = 2000,
  typehierarchy = {
    layout = "float",
    left_width = 0.2,
    keys = {
      edit = "e",
      vsplit = "s",
      split = "i",
      tabe = "t",
      close = "<C-c>k",
      quit = "q",
      shuttle = "[w",
      toggle_or_req = "u",
    },
  },
  floaterm = {
    height = 0.7,
    width = 0.7,
  },
  finder = {
    max_height = 0.5,
    left_width = 0.4,
    right_width = 0.3,
    default = "ref+imp",
    methods = {},
    layout = "float",
    filter = {},
    silent = false,
    fname_sub = nil,
    sp_inexist = false,
    sp_global = false,
    ly_botright = false,
    number = vim.o.number,
    relativenumber = vim.o.relativenumber,
    keys = {
      shuttle = "[w",
      toggle_or_open = "o",
      vsplit = "s",
      split = "i",
      tabe = "t",
      tabnew = "r",
      quit = "q",
      close = "<C-c>k",
    },
  },
  diagnostic = {
    show_code_action = true,
    jump_num_shortcut = true,
    max_width = 0.8,
    max_height = 0.6,
    text_hl_follow = true,
    border_follow = true,
    extend_relatedInformation = false,
    show_layout = "float",
    show_normal_height = 10,
    max_show_width = 0.9,
    max_show_height = 0.6,
    diagnostic_only_current = false,
    auto_preview = false,
    wrap_long_lines = true,
    keys = {
      exec_action = "o",
      quit = "q",
      toggle_or_jump = "<CR>",
      quit_in_show = { "q", "<ESC>" },
    },
  },
  definition = {
    width = 0.6,
    height = 0.5,
    save_pos = false,
    number = vim.o.number,
    relativenumber = vim.o.relativenumber,
    keys = {
      edit = "<C-o>",
      vsplit = "<C-v>",
      split = "<C-x>",
      tabe = "<C-t>",
      tabnew = "<C-c>n",
      quit = "q",
      close = "<ESC>",
    },
  },
  hover = {
    max_width = 0.9,
    max_height = 0.8,
    open_link = "gx",
    open_cmd = "!chrome",
  },
  rename = {
    in_select = true,
    auto_save = false,
    project_max_width = 0.5,
    project_max_height = 0.5,
    keys = {
      quit = "<C-k>",
      exec = "<CR>",
      select = "x",
    },
  },
  callhierarchy = {
    layout = "float",
    left_width = 0.2,
    keys = {
      edit = "e",
      vsplit = "s",
      split = "i",
      tabe = "t",
      close = "<C-c>k",
      quit = "q",
      shuttle = "[w",
      toggle_or_req = "u",
    },
  },
  code_action = {
    num_shortcut = true,
    show_server_name = false,
    extend_gitsigns = false,
    only_in_cursor = true,
    max_height = 0.3,
    cursorline = true,
    keys = {
      quit = "q",
      exec = "<CR>",
    },
  },
  lightbulb = {
    enable = true,
    sign = true,
    virtual_text = true,
    debounce = 10,
    sign_priority = 40,
    enable_in_insert = true,
    ignore = {
      clients = {},
      ft = {},
    },
  },
  symbol_in_winbar = {
    enable = true,
    separator = " › ",
    hide_keyword = false,
    show_file = true,
    folder_level = 1,
    color_mode = true,
    delay = 300,
    ignore_patterns = nil,
  },
  outline = {
    win_position = "right",
    win_width = 30,
    auto_preview = true,
    detail = true,
    auto_close = true,
    close_after_jump = false,
    layout = "normal",
    max_height = 0.5,
    left_width = 0.3,
    keys = {
      toggle_or_jump = "o",
      quit = "q",
      jump = "e",
    },
  },
  implement = {
    enable = true,
    sign = true,
    virtual_text = true,
    priority = 100,
    lang = {},
  },
  ui = {
    border = "rounded",
    devicon = true,
    title = true,
    expand = "⊞",
    collapse = "⊟",
    code_action = "💡",
    actionfix = " ",
    lines = { "┗", "┣", "┃", "━", "┏" },
    kind = nil,
    imp_sign = "󰳛 ",
    winbar_prefix = "",
    foldericon = true,
    button = { "", "" },
    use_nerd = true,
  },
  beacon = {
    enable = true,
    frequency = 7,
  },
}

return opts
