---@type table
local cmds = {
  "BarbarDisable",
  "BarbarEnable",
  "BufferClose",
  "BufferCloseAllButCurrent",
  "BufferCloseAllButCurrentOrPinned",
  "BufferCloseAllButPinned",
  "BufferCloseAllButVisible",
  "BufferCloseBuffersLeft",
  "BufferCloseBuffersRight",
  "BufferFirst",
  "BufferGoto",
  "BufferGotoPinned",
  "BufferGotoUnpinned",
  "BufferLast",
  "BufferMove",
  "BufferMoveNext",
  "BufferMovePrevious",
  "BufferMoveStart",
  "BufferNext",
  "BufferOrderByBufferNumber",
  "BufferOrderByDirectory",
  "BufferOrderByLanguage",
  "BufferOrderByName",
  "BufferOrderByWindowNumber",
  "BufferPick",
  "BufferPickDelete",
  "BufferPin",
  "BufferPrevious",
  "BufferRestore",
  "BufferScrollLeft",
  "BufferScrollRight",
  "BufferWipeout",
}

return cmds
